### PR TITLE
GH-33 updated the buildroot directory to version 2023.02.1

### PR DESCRIPTION
**Pull request by svenrademakers**
updated the buildroot version to the latest. The main driver for this was the out-of-date rust toolchain. 

no additional patches are applied.

### CODE REVIEW

**Review by ruslashev — APPROVED** [review]
Still unsure if we should stick to an archived buildroot-2023.02.1.tar.gz or a decompressed folder. Regardless, this works for now and we need this from CHANGES:

> Cargo: CARGO_HOME (the location where cargo stores it
    downloaded artifacts) is now located under DL_DIR rather
    than in HOST_DIR/share/cargo, ensuring it is shared between
    builds.

**Comment by svenrademakers** [comment]
Could you give me any pointers where these dot files are supposed to be? There where no buildroot/.* files being committed to git before

**Comment by ruslashev** [comment]
Just in their repository, e.g. the [mirror](https://github.com/buildroot/buildroot)

**Comment by svenrademakers** [comment]
added the .gitignore to the root of the ./buildroot folder. Could you verify everything is oke and approve the PR if you are satisfied?

**Review by ruslashev — APPROVED** [review]

**Pull request merged**
